### Create a new user
POST http://localhost:3000/auth/signin
Content-type: application/json

{
    "email": "319271103130@qq.com",
    "password": "3192703130"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/25

### Find all users with a given email
GET http://localhost:3000/auth?email=3192703130@qq.com

### Update a user
PATCH http://localhost:3000/auth/24
Content-type: application/json

{
    "email": "mhj@qq.com",
    "password": "000000"
}

### Delete a user given id
DELETE http://localhost:3000/auth/24